version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:22.0.5
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      volumes:
        - ./themes/:/opt/keycloak/themes/
      command: [
        "start-dev",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false"
      ]
